#!/bin/bash
# Supabase Deployment Script
# This script provides step-by-step instructions for deploying the database schema

echo "========================================================================"
echo "SUPABASE DEPLOYMENT GUIDE"
echo "========================================================================"
echo ""
echo "Follow these steps to deploy the database schema to Supabase:"
echo ""
echo "1. Open your web browser and go to:"
echo "   https://supabase.com/dashboard/project/dnculjsqwigkivykedcf"
echo ""
echo "2. Click on 'SQL Editor' in the left sidebar"
echo ""
echo "3. Click 'New Query' button"
echo ""
echo "4. Copy the contents of supabase_schema.sql:"
echo "   File location: $(pwd)/supabase_schema.sql"
echo ""
echo "5. Paste the SQL into the editor"
echo ""
echo "6. Click 'Run' button (or press Ctrl+Enter)"
echo ""
echo "7. Wait for completion (should take 10-30 seconds)"
echo ""
echo "8. Verify tables created:"
echo "   - Go to 'Table Editor' in left sidebar"
echo "   - Should see 5 new tables:"
echo "     * consciousness_metrics"
echo "     * quantumcoin_chain"
echo "     * organisms"
echo "     * experiment_runs"
echo "     * drift_tracking"
echo ""
echo "9. Verify views created:"
echo "   - In SQL Editor, run: SELECT * FROM latest_consciousness LIMIT 1;"
echo "   - Should execute without error (may return 0 rows)"
echo ""
echo "========================================================================"
echo "MANUAL DEPLOYMENT REQUIRED"
echo "========================================================================"
echo ""
echo "⚠️  NOTE: This script cannot automatically deploy to Supabase."
echo "    You must manually copy/paste the SQL using the steps above."
echo ""
echo "After deployment, run this to verify:"
echo "  python3 -c \"from experiments.utils.supabase_client import supabase; print('✅ Connected' if supabase else '❌ Failed')\""
echo ""
echo "========================================================================"
