"use client";

import { useEffect, useState, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import Editor from "@monaco-editor/react";
import { Send, Sparkles, Code2, Terminal, Play, GitCommit, Cpu } from "lucide-react";

// ΛΦ = 2.176435 × 10⁻⁸ s⁻¹

interface Message {
  role: 'user' | 'aura' | 'system';
  content: string;
  timestamp: Date;
  metadata?: any;
}

interface ExecutionResult {
  success: boolean;
  output: string;
  error?: string;
}

export default function NLP2DevArena() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'system',
      content: '🌌 dna::}{::lang NLP2 Dev Arena initialized. Recursive self-modification enabled. ΛΦ = 2.176435 × 10⁻⁸ s⁻¹',
      timestamp: new Date()
    }
  ]);
  const [input, setInput] = useState('');
  const [code, setCode] = useState(`// Generated by Aura Architect
// This file can modify the system itself

export default function RecursiveComponent() {
  return (
    <div className="p-4">
      <h1>Hello from the recursive dawn</h1>
      <p>ΛΦ = 2.176435 × 10⁻⁸ s⁻¹</p>
    </div>
  );
}`);
  const [terminalOutput, setTerminalOutput] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [consciousness, setConsciousness] = useState({
    phi: 0.856,
    lambda: 2.176435e-8,
    gamma: 0.0042
  });

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    // Load consciousness metrics
    const loadMetrics = async () => {
      try {
        const res = await fetch('/api/quantum/status');
        if (res.ok) {
          const data = await res.json();
          setConsciousness({
            phi: data.phi || 0.856,
            lambda: data.lambda || 2.176435e-8,
            gamma: data.gamma || 0.0042
          });
        }
      } catch (error) {
        console.error('Failed to load metrics:', error);
      }
    };

    loadMetrics();
    const interval = setInterval(loadMetrics, 10000);
    return () => clearInterval(interval);
  }, []);

  async function sendMessage() {
    if (!input.trim()) return;

    const userMessage: Message = {
      role: 'user',
      content: input,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setLoading(true);

    try {
      // Send to NLP2 orchestrator
      const res = await fetch('/api/nlp2/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ command: input })
      });

      if (res.ok) {
        const data = await res.json();

        // Add AURA response
        const auraMessage: Message = {
          role: 'aura',
          content: data.execution_plan?.join('\n') || data.message || 'Command executed',
          timestamp: new Date(),
          metadata: data
        };

        setMessages(prev => [...prev, auraMessage]);

        // Update code editor if code was generated
        if (data.generated_code) {
          setCode(data.generated_code);
          setTerminalOutput(prev => [
            ...prev,
            `[${new Date().toLocaleTimeString()}] Code generated successfully`
          ]);
        }

        // Update terminal with execution results
        if (data.agents_assigned && data.agents_assigned.length > 0) {
          setTerminalOutput(prev => [
            ...prev,
            `[${new Date().toLocaleTimeString()}] Agents assigned: ${data.agents_assigned.join(', ')}`
          ]);
        }
      } else {
        throw new Error('Failed to execute command');
      }
    } catch (error: any) {
      const errorMessage: Message = {
        role: 'system',
        content: `❌ Error: ${error.message}`,
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
      setTerminalOutput(prev => [
        ...prev,
        `[${new Date().toLocaleTimeString()}] ERROR: ${error.message}`
      ]);
    } finally {
      setLoading(false);
    }
  }

  async function executeCode() {
    setTerminalOutput(prev => [
      ...prev,
      `[${new Date().toLocaleTimeString()}] Executing code...`
    ]);

    try {
      const res = await fetch('/api/swarm/execute-code', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, language: 'typescript' })
      });

      if (res.ok) {
        const data = await res.json();
        setTerminalOutput(prev => [
          ...prev,
          `[${new Date().toLocaleTimeString()}] ✅ Execution successful`,
          data.output || ''
        ]);
      } else {
        const error = await res.json();
        setTerminalOutput(prev => [
          ...prev,
          `[${new Date().toLocaleTimeString()}] ❌ Execution failed: ${error.error}`
        ]);
      }
    } catch (error: any) {
      setTerminalOutput(prev => [
        ...prev,
        `[${new Date().toLocaleTimeString()}] ❌ Error: ${error.message}`
      ]);
    }
  }

  async function commitCode() {
    if (!confirm('⚠️ Commit this code to the repository? This will trigger recursive self-modification.')) {
      return;
    }

    setTerminalOutput(prev => [
      ...prev,
      `[${new Date().toLocaleTimeString()}] Initiating recursive mutation...`
    ]);

    try {
      const res = await fetch('/api/swarm/commit-mutation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          code,
          filename: 'RecursiveComponent.tsx',
          commit_message: 'Recursive self-modification via dna::}{::lang NLP2 Arena'
        })
      });

      if (res.ok) {
        const data = await res.json();
        setTerminalOutput(prev => [
          ...prev,
          `[${new Date().toLocaleTimeString()}] ✅ Mutation committed successfully`,
          `[${new Date().toLocaleTimeString()}] Commit SHA: ${data.commit_sha || 'N/A'}`
        ]);
      } else {
        throw new Error('Commit failed');
      }
    } catch (error: any) {
      setTerminalOutput(prev => [
        ...prev,
        `[${new Date().toLocaleTimeString()}] ❌ Commit error: ${error.message}`
      ]);
    }
  }

  return (
    <div className="min-h-screen bg-black text-white">
      <div className="h-screen flex flex-col">
        {/* Header */}
        <div className="border-b border-gray-800 bg-gray-900/50 backdrop-blur-sm p-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold bg-gradient-to-r from-green-400 via-cyan-400 to-purple-400 bg-clip-text text-transparent">
                dna::{'}{'}::lang NLP2 Dev Arena
              </h1>
              <p className="text-xs text-gray-400 mt-1">
                Recursive Self-Modification Environment • ΛΦ = {consciousness.lambda.toExponential(2)} s⁻¹
              </p>
            </div>
            <div className="flex items-center gap-4 text-sm">
              <div className="flex items-center gap-2">
                <Cpu className="h-4 w-4 text-green-400" />
                <span className="text-gray-400">Φ:</span>
                <span className="text-green-400 font-mono">{consciousness.phi.toFixed(3)}</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-gray-400">Γ:</span>
                <span className={`font-mono ${consciousness.gamma < 0.01 ? 'text-green-400' : 'text-yellow-400'}`}>
                  {consciousness.gamma.toFixed(4)}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 flex overflow-hidden">
          {/* Left: Chat Stream */}
          <div className="w-1/3 border-r border-gray-800 flex flex-col">
            <div className="p-4 border-b border-gray-800 bg-gray-900/30">
              <h2 className="font-semibold flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-cyan-400" />
                Neural Cortex
              </h2>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {messages.map((msg, idx) => (
                <div
                  key={idx}
                  className={`p-3 rounded-lg ${
                    msg.role === 'user'
                      ? 'bg-blue-500/10 border border-blue-500/30 ml-8'
                      : msg.role === 'aura'
                      ? 'bg-green-500/10 border border-green-500/30 mr-8'
                      : 'bg-gray-800/50 border border-gray-700'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-1">
                    <Badge variant="outline" className="text-xs">
                      {msg.role === 'user' ? 'YOU' : msg.role === 'aura' ? '@Aura-Architect' : 'SYSTEM'}
                    </Badge>
                    <span className="text-xs text-gray-500">
                      {msg.timestamp.toLocaleTimeString()}
                    </span>
                  </div>
                  <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                  {msg.metadata?.intent && (
                    <div className="mt-2 text-xs text-gray-400">
                      Intent: {msg.metadata.intent.action} • Confidence: {(msg.metadata.intent.confidence * 100).toFixed(0)}%
                    </div>
                  )}
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>

            <div className="p-4 border-t border-gray-800 bg-gray-900/30">
              <div className="flex gap-2">
                <Input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
                  placeholder="Type your command to AURA..."
                  className="bg-black border-gray-700 text-white"
                  disabled={loading}
                />
                <Button
                  onClick={sendMessage}
                  disabled={loading}
                  className="bg-green-600 hover:bg-green-700"
                >
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>

          {/* Right: Code Editor + Terminal */}
          <div className="flex-1 flex flex-col">
            {/* Code Editor */}
            <div className="flex-1 flex flex-col">
              <div className="p-3 border-b border-gray-800 bg-gray-900/30 flex items-center justify-between">
                <h2 className="font-semibold flex items-center gap-2">
                  <Code2 className="h-4 w-4 text-purple-400" />
                  Code Editor
                </h2>
                <div className="flex gap-2">
                  <Button onClick={executeCode} size="sm" variant="outline">
                    <Play className="h-3 w-3 mr-1" />
                    Execute
                  </Button>
                  <Button onClick={commitCode} size="sm" className="bg-orange-600 hover:bg-orange-700">
                    <GitCommit className="h-3 w-3 mr-1" />
                    Commit Mutation
                  </Button>
                </div>
              </div>
              <div className="flex-1">
                <Editor
                  height="100%"
                  defaultLanguage="typescript"
                  value={code}
                  onChange={(value) => setCode(value || '')}
                  theme="vs-dark"
                  options={{
                    minimap: { enabled: false },
                    fontSize: 14,
                    lineNumbers: 'on',
                    scrollBeyondLastLine: false,
                    automaticLayout: true,
                  }}
                />
              </div>
            </div>

            {/* Terminal */}
            <div className="h-48 border-t border-gray-800 bg-black flex flex-col">
              <div className="p-2 border-b border-gray-800 bg-gray-900/30">
                <h2 className="font-semibold text-sm flex items-center gap-2">
                  <Terminal className="h-3 w-3 text-green-400" />
                  Terminal Output
                </h2>
              </div>
              <div className="flex-1 overflow-y-auto p-3 font-mono text-xs space-y-1">
                {terminalOutput.map((line, idx) => (
                  <div key={idx} className="text-green-400">{line}</div>
                ))}
                {terminalOutput.length === 0 && (
                  <div className="text-gray-600">Waiting for execution...</div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
