apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnalang-frontend
  namespace: dnalang-quantum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnalang-frontend
  template:
    metadata:
      labels:
        app: dnalang-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: dnalang-frontend
  namespace: dnalang-quantum
spec:
  selector:
    app: dnalang-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
